import { loadAppVersion } from "./services/appVersionProvider.js";

const reportUrls = ["/reports/latest-weekly-report.json", "/public/reports/latest-weekly-report.json"];
const artifactLinks = {
  reportJson: "/reports/latest-weekly-report.json",
  reportText: "/reports/latest-weekly-report.txt",
  emailHtml: "/reports/latest-weekly-email.html",
  emailText: "/reports/latest-weekly-email.txt"
};

const app = document.querySelector("#report-app");

if (!app) {
  throw new Error("Report app root not found");
}

function formatDateTime(value) {
  if (!value) {
    return "Unknown";
  }

  const date = new Date(value);
  if (Number.isNaN(date.getTime())) {
    return value;
  }

  return new Intl.DateTimeFormat("zh-Hant-HK", {
    dateStyle: "medium",
    timeStyle: "short",
    timeZone: "Asia/Hong_Kong"
  }).format(date);
}

function escapeHtml(value) {
  return String(value ?? "")
    .replaceAll("&", "&amp;")
    .replaceAll("<", "&lt;")
    .replaceAll(">", "&gt;")
    .replaceAll("\"", "&quot;")
    .replaceAll("'", "&#39;");
}

async function fetchJson(url) {
  const response = await fetch(url, { cache: "no-store" });
  if (!response.ok) {
    throw new Error(`Report fetch failed: ${response.status}`);
  }

  return response.json();
}

async function loadReport() {
  for (const reportUrl of reportUrls) {
    try {
      return await fetchJson(reportUrl);
    } catch {
      continue;
    }
  }

  throw new Error("No weekly report artifact found.");
}

function renderVersionBadge(appVersion) {
  const label = appVersion?.label ?? "local";
  return `<span class="version-badge" title="Build ${appVersion?.buildId ?? label}">v ${label}</span>`;
}

function renderArtifactLinks() {
  return `
    <div class="report-actions">
      <a href="${artifactLinks.reportJson}">Report JSON</a>
      <a href="${artifactLinks.reportText}">Report TXT</a>
      <a href="${artifactLinks.emailHtml}">Email HTML</a>
      <a href="${artifactLinks.emailText}">Email TXT</a>
      <a href="/">Dashboard</a>
    </div>
  `;
}

function renderSummaryCards(report) {
  const cards = [
    ["Report generated", formatDateTime(report.generatedAt)],
    ["Tier", report.tier ?? "unknown"],
    ["Symbols", report.symbols?.length ?? report.summary?.total ?? 0],
    ["PR > SMA1", report.summary?.improvingCount ?? 0],
    ["Above month line", report.summary?.aboveMonthCount ?? 0],
    ["Source", report.source ?? "unknown"]
  ];

  return `
    <section class="report-card-grid">
      ${cards
        .map(
          ([label, value]) => `
            <article class="report-stat">
              <span>${escapeHtml(label)}</span>
              <strong>${escapeHtml(value)}</strong>
            </article>
          `
        )
        .join("")}
    </section>
  `;
}

function renderSymbolTable(report) {
  const details = report.symbolDetails ?? [];
  if (details.length === 0) {
    return `<p class="side-note">No symbol details in this report artifact.</p>`;
  }

  return `
    <div class="report-table-wrap">
      <table class="report-table">
        <thead>
          <tr>
            <th>Symbol</th>
            <th>動能指數</th>
            <th>Status</th>
            <th>Signal</th>
            <th>月線距離</th>
            <th>As of</th>
          </tr>
        </thead>
        <tbody>
          ${details
            .map(
              (item) => `
                <tr>
                  <td>
                    <strong>${escapeHtml(item.symbol)}</strong>
                    <span>${escapeHtml(item.displayName)}</span>
                  </td>
                  <td>${escapeHtml(item.prValue)}</td>
                  <td>${escapeHtml(item.status)}</td>
                  <td>${escapeHtml(item.signal)}</td>
                  <td>${escapeHtml(item.distanceToMonthPct)}%</td>
                  <td>${escapeHtml(item.asOf)}</td>
                </tr>
              `
            )
            .join("")}
        </tbody>
      </table>
    </div>
  `;
}

function renderDigest(report) {
  return `
    <article class="panel report-digest">
      <h3>Text Digest</h3>
      <pre>${escapeHtml(report.digestText ?? "")}</pre>
    </article>
  `;
}

function renderReport(report, appVersion) {
  app.innerHTML = `
    <div class="report-shell">
      <header class="report-header">
        <div>
          <span class="brand-kicker">Math of Stars ${renderVersionBadge(appVersion)}</span>
          <h1>Report Preview</h1>
          <p>Latest weekly digest and email artifacts generated by the dashboard pipeline.</p>
        </div>
        ${renderArtifactLinks()}
      </header>

      ${renderSummaryCards(report)}

      <main class="report-layout">
        <section class="report-main-column">
          <article class="panel">
            <h3>Symbol Snapshot</h3>
            ${renderSymbolTable(report)}
          </article>
          ${renderDigest(report)}
        </section>

        <section class="report-preview-column">
          <article class="panel report-email-panel">
            <h3>Email HTML Preview</h3>
            <iframe
              class="email-preview-frame"
              title="Weekly email preview"
              src="${artifactLinks.emailHtml}"
            ></iframe>
          </article>
        </section>
      </main>

      <footer class="footer-note">
        圖表閱讀、教育及研究用途，不構成投資建議。
      </footer>
    </div>
  `;
}

function renderError(error) {
  app.innerHTML = `
    <div class="report-shell">
      <header class="report-header">
        <div>
          <span class="brand-kicker">Math of Stars</span>
          <h1>Report Preview</h1>
        </div>
        ${renderArtifactLinks()}
      </header>
      <article class="panel">
        <h3>Report artifact unavailable</h3>
        <p>${escapeHtml(error.message)}</p>
      </article>
    </div>
  `;
}

async function boot() {
  try {
    const [report, appVersion] = await Promise.all([loadReport(), loadAppVersion()]);
    renderReport(report, appVersion);
  } catch (error) {
    renderError(error);
  }
}

void boot();
